CREATE TABLE IF NOT EXISTS books(
    id VARCHAR(255) PRIMARY KEY,
    title JSON NOT NULL,
    author JSON NOT NULL,
    publisher JSON NOT NULL,
    isbn JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);